DROP TABLE IF EXISTS junk CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS usergroups CASCADE;
DROP TABLE IF EXISTS user_in_group CASCADE;
DROP TABLE IF EXISTS configure CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
--DROP TABLE IF EXISTS grouprelations CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS subscriptions_all CASCADE;
DROP TABLE IF EXISTS subscriptions_pauseid CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS tag_cloud CASCADE;

DROP SEQUENCE IF EXISTS groups_id_seq;
DROP SEQUENCE IF EXISTS posts_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS usergroups_id_seq;
DROP SEQUENCE IF EXISTS authors_id_seq;
DROP SEQUENCE IF EXISTS subscriptions_id_seq;
DROP SEQUENCE IF EXISTS subscriptions_all_id_seq;
DROP SEQUENCE IF EXISTS subscriptions_pauseid_id_seq;
DROP SEQUENCE IF EXISTS tags_id_seq;


